# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b145e121472c19b1e73c9d41ba41fbd85e8e43d85bbc0c884c1cf03f613f7e06e1f0e694d2c9bcf5b9407a5c0a277cd8206fd8a7978782892c53cf3e00bb4919

test:
  secret_key_base: 19b151ccfa2e25ac6e5b21babd3ecd399b92466bedd02c338f4853037d4724fe24e022c3de9b4274346f35dc9cc5f46cf1d3140313abb1771fe407254a4403e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
